# Generated by Django 4.2.30 on 2026-10-04 22:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('focus', models.CharField(choices=[('abs', 'Abs'), ('chest', 'Chest'), ('arms', 'Arms'), ('legs', 'Legs'), ('shoulder_back', 'Shoulder & Back')], max_length=20)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20)),
                ('start_date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_challenges', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveSmallIntegerField()),
                ('title', models.CharField(max_length=100)),
                ('duration_minutes', models.PositiveSmallIntegerField()),
                ('exercise_count', models.PositiveSmallIntegerField()),
                ('calories_burned', models.PositiveSmallIntegerField()),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to='workouts.challenge')),
            ],
            options={
                'ordering': ['-completed_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='workout',
            constraint=models.UniqueConstraint(fields=('challenge', 'day_number'), name='unique_challenge_workout_day'),
        ),
        migrations.AddConstraint(
            model_name='workout',
            constraint=models.CheckConstraint(check=models.Q(('day_number__gte', 1), ('day_number__lte', 28)), name='workout_day_is_within_challenge'),
        ),
        migrations.AddConstraint(
            model_name='challenge',
            constraint=models.UniqueConstraint(fields=('user', 'focus', 'difficulty'), name='unique_user_focus_difficulty_challenge'),
        ),
    ]
