# Generated by Django 4.2.30 on 2026-10-05 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='calories_burned',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
